spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/../../../Users/chldb/cheongwon
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: false
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace

univCert:
  key: 6ccf4452-46d2-48d5-9437-f83b3a732c82

jwt:
  secret: u9jN23kLso2P7q1aN7K72mH5sQ8J2XN9o3K7VtL+F2I=sdfjksaldfjksddjflskfjsfldksdfjsdf
  accessExpiration: 3600000 #1시간
  refreshExpiration: 86400000 #1일