# main으로 merge 혹은 main에서 코드 변경 시 실행
# aws ec2로 배포하는 workflow
# 실제 배포에서 사용되면 yaml 파일은 인스턴스 안에 있는 application-prod.yml (클러스터 문제 해결되면 여기 파일을 dev로 바꿔줘야 함)

name: Deploy to AWS EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3
      
      # JDK 설정
      - name: JDK 21 설정
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Gradle 권한 부여
        run: chmod +x ./gradlew
        
      - name: Gradle 캐싱
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      # application.yml 파일 생성
      - name: application.yml 생성
        env:
          YAML_CONTENT: ${{secrets.YAML_PROD}}
        run: |
          mkdir -p src/main/resources
          echo "$YAML_CONTENT" > src/main/resources/application.yml
      
      - name: Build JAR
        run: ./gradlew clean build
      
      - name: Configure SSH Key
        env:
          PEM_KEY: ${{ secrets.AWS_PEM_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$PEM_KEY" > ~/.ssh/aws_key.pem
          chmod 600 ~/.ssh/aws_key.pem
      
      - name: Add EC2 to Known Hosts
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh-keyscan $EC2_HOST >> ~/.ssh/known_hosts
      
      - name: Transfer JAR to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          scp -i ~/.ssh/aws_key.pem ./build/libs/hufs_cheongwon-0.0.1-SNAPSHOT.jar $EC2_USER@$EC2_HOST:/home/$EC2_USER/app/

      - name: Restart Application on EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -i ~/.ssh/aws_key.pem $EC2_USER@$EC2_HOST <<EOF
          echo "애플리케이션 배포 스크립트 실행 중..."
          ./deploy.sh
          EOF
